In [1]:
import numpy as np

In [2]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
z = np.flip(z)
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [4]:
z = np.reshape(z, (10,4))
print(z)

[[49 48 47 46]
 [45 44 43 42]
 [41 40 39 38]
 [37 36 35 34]
 [33 32 31 30]
 [29 28 27 26]
 [25 24 23 22]
 [21 20 19 18]
 [17 16 15 14]
 [13 12 11 10]]


In [5]:
x = np.array([5,6,8,0,1,0,7])
nz_idx = x[0:3], x[4:7:2]
print(nz_idx)

(array([5, 6, 8]), array([1, 7]))


In [7]:
print(np.nan == np.nan)
print(np.isnan(np.nan))

import math
print(0.3 == 3 * 0.1)
print(math.isclose(0.1 + 0.2, 0.3))
print(math.isnan(np.nan))

a = np.array([1, np.nan, 3, np.nan, 5])
a[np.isnan(a)] = 999
print(a)

False
True
False
True
True
[  1. 999.   3. 999.   5.]


In [8]:
x = np.zeros((12,12))
print(x, end = '\n\n')
for i in range(12):
    if i % 2 == 0:
        x[i,1::2] = 1
    else:
        x[i,0::2] = 1
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


In [9]:
x = np.tile(np.array([[0, 1], [1, 0]]),(12, 12))
print(x)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1

In [11]:
x = np.array([2,5,3,8,3,34,23,7,10])
print(x)

filtering = [1,3,7,8] 
x[filtering] = 0
print(x)

[ 2  5  3  8  3 34 23  7 10]
[ 2  0  3  0  3 34 23  0  0]


In [12]:
x = np.linspace(0,100,10)
print(x)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [13]:
A = np.array([1e10, 1e-8])
B = np.array([1.00001e10, 1e-9])

equal = np.allclose(A, B)
print(equal)

True


In [14]:
coord = np.random.random((10,2))
x, y = coord[:,0], coord[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan(y,x)
polar_coord = np.concatenate([r[:,np.newaxis], theta[:,np.newaxis]], axis=1)
print(polar_coord)

[[1.11121394 0.72445703]
 [0.65186743 0.56627656]
 [0.83122691 0.56893387]
 [0.22626622 0.19770088]
 [0.98032114 0.6189118 ]
 [0.26271749 0.09850029]
 [0.9749048  0.30938353]
 [0.73354837 0.13686666]
 [0.67497147 0.42232643]
 [0.93465416 0.62111002]]
